---
                                            Московский Авиационный Институт  
                                      (Национальный Исследовательский Университет)  
        
                
                 
    Институт №8 «Информационные технологии и прикладная математика»  
    Кафедра 806 «Вычислительная математика и программирование» 
    Дисциплина: «Разработка ПО для высокопроизводительных систем»        
                



                                            Лабораторная работа по Numpy №3  
    
                                            
                                            
                                            
                                                                                Группа: М8О-103М-20  
                                                                                Студент: Никитина Анна Евгеньевна  
                                                                                Преподаватель: Поповкин Александр Викторович  
                                                                                
                                                                                
                                                                                
                                                     Москва, 2020  
                                                         
--- 

In [3]:
import numpy as np

1. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [7]:
a=np.array([1, 2, 3, 4, 5])
nz = 3
a0 = np.zeros(len(a) + (len(a)-1)*(nz))
a0[::nz+1] = a
print(a0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


2. Поменять 2 строки в матрице

In [16]:
a=np.array(([1, 2, 3],[4, 6, 8],[1, 3, 5]))
a[[0,1]]=a[[1,0]]
print(a)

[[4 6 8]
 [1 2 3]
 [1 3 5]]


3. Рассмотрим набор из 10 троек, описывающих 10 треугольников (с общими вершинами), найти множество уникальных отрезков, составляющих все треугольники

In [18]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)
print(faces)

[( 3, 62) ( 3, 77) ( 6, 42) ( 6, 79) (17, 31) (17, 59) (18, 54) (18, 69)
 (20, 49) (20, 71) (27, 32) (27, 55) (31, 59) (32, 55) (33, 36) (33, 46)
 (36, 46) (42, 79) (45, 47) (45, 96) (47, 96) (49, 71) (54, 69) (58, 63)
 (58, 92) (60, 77) (60, 82) (62, 77) (63, 92) (77, 82)]
[[59 31 17]
 [96 45 47]
 [69 54 18]
 [92 58 63]
 [ 6 42 79]
 [ 3 77 62]
 [32 55 27]
 [20 49 71]
 [82 77 60]
 [36 46 33]]


4. Дан массив C; создать массив A, что np.bincount(A) == C

In [20]:
C = np.bincount([1,2,3,4,5,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 2 3 4 5 6]


5. Посчитать среднее, используя плавающее окно

In [28]:
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    print(ret)
    ret[n:] = ret[n:] - ret[:-n]
    print(ret[n:])
    print(ret[n - 1:])
    return ret[n - 1:] / n

print(moving_average(np.arange(5), 3))

[ 0.  1.  3.  6. 10.]
[ 6. 10.]
[ 3.  6. 10.]
[1.         2.         3.33333333]


6. Дан вектор Z, построить матрицу, первая строка которой (Z[0],Z[1],Z[2]), каждая последующая сдвинута на 1 (последняя (Z[-3],Z[-2],Z[-1]))


In [32]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


7. Инвертировать булево значение, или поменять знак у числового массива без создания нового

In [15]:
a = np.random.randint(0,2,5)
print(a)
print(np.logical_not(a, out=a))

b = np.random.uniform(-1.0,1.0,5)
print(b)
print(np.negative(b, out=b))

[0 1 0 1 1]
[1 0 1 0 0]
[-0.25856161 -0.47642577  0.94000641  0.64246551 -0.53202756]
[ 0.25856161  0.47642577 -0.94000641 -0.64246551  0.53202756]


8. Посчитать ранг матрицы

In [5]:
a = np.random.uniform(0,1,(10,10))
rank = np.linalg.matrix_rank(a)
print(rank)

10


9. Найти наиболее частое значение в массиве

In [7]:
a = np.random.randint(0,7,15)
print(np.bincount(a).argmax())

6


10. Извлечь все смежные 3x3 блоки из 10x10 матрицы

In [21]:
a = np.random.randint(0,5,(10,10))
print(a)
n = 3
i = 1 + (a.shape[0] - n)
j = 1 + (a.shape[1] - n)
C = np.lib.stride_tricks.as_strided(a, shape=(i, j, n, n), strides=a.strides + a.strides)
print(C)

[[3 1 2 0 3 1 1 2 1 0]
 [4 3 4 3 3 4 0 2 2 2]
 [2 2 1 1 3 3 2 2 0 3]
 [1 4 4 3 2 1 2 1 1 3]
 [3 4 0 1 2 0 1 1 0 0]
 [4 2 4 2 3 0 4 1 2 3]
 [0 1 2 3 2 3 2 4 0 1]
 [3 0 1 3 2 3 1 4 3 1]
 [0 3 4 4 1 1 2 4 3 4]
 [3 2 2 4 4 1 2 3 0 4]]
[[[[3 1 2]
   [4 3 4]
   [2 2 1]]

  [[1 2 0]
   [3 4 3]
   [2 1 1]]

  [[2 0 3]
   [4 3 3]
   [1 1 3]]

  [[0 3 1]
   [3 3 4]
   [1 3 3]]

  [[3 1 1]
   [3 4 0]
   [3 3 2]]

  [[1 1 2]
   [4 0 2]
   [3 2 2]]

  [[1 2 1]
   [0 2 2]
   [2 2 0]]

  [[2 1 0]
   [2 2 2]
   [2 0 3]]]


 [[[4 3 4]
   [2 2 1]
   [1 4 4]]

  [[3 4 3]
   [2 1 1]
   [4 4 3]]

  [[4 3 3]
   [1 1 3]
   [4 3 2]]

  [[3 3 4]
   [1 3 3]
   [3 2 1]]

  [[3 4 0]
   [3 3 2]
   [2 1 2]]

  [[4 0 2]
   [3 2 2]
   [1 2 1]]

  [[0 2 2]
   [2 2 0]
   [2 1 1]]

  [[2 2 2]
   [2 0 3]
   [1 1 3]]]


 [[[2 2 1]
   [1 4 4]
   [3 4 0]]

  [[2 1 1]
   [4 4 3]
   [4 0 1]]

  [[1 1 3]
   [4 3 2]
   [0 1 2]]

  [[1 3 3]
   [3 2 1]
   [1 2 0]]

  [[3 3 2]
   [2 1 2]
   [2 0 1]]

  [[3 2 2]
   [1 2 1]
   [0 1 

11. Рассмотрим множество матриц (n,n) и множество из p векторов (n,1). Посчитать сумму p произведений матриц (результат имеет размерность (n,1))

In [37]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


12. Дан массив 16x16, посчитать сумму по блокам 4x4

In [17]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


13. Найти n наибольших значений в массиве

In [19]:
Z = np.arange(100)
np.random.shuffle(Z)
n = 5
print (Z[np.argpartition(-Z,n)[:n]])

[97 96 99 98 95]


14. Построить прямое произведение массивов (все комбинации с каждым элементом)

In [20]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = map(len, arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print(cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


15. Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B


In [42]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
print(A)
print(B)
C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
#print(C)
print(rows)

[[4 1 2]
 [1 2 1]
 [1 1 0]
 [4 4 4]
 [3 3 3]
 [4 0 3]
 [1 2 2]
 [3 1 0]]
[[3 2]
 [3 1]]
[0 1 2 4 5 6 7]


16. Дана 10x3 матрица, найти строки из неравных значений (например [2,2,3])


In [38]:
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[4 1 2]
 [2 0 3]
 [3 0 4]
 [0 3 2]
 [3 2 0]
 [3 3 0]
 [3 3 1]
 [4 4 2]
 [4 4 0]
 [3 4 1]]
[[4 1 2]
 [2 0 3]
 [3 0 4]
 [0 3 2]
 [3 2 0]
 [3 3 0]
 [3 3 1]
 [4 4 2]
 [4 4 0]
 [3 4 1]]


17. Преобразовать вектор чисел в матрицу бинарных представлений

In [23]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


18. Дан двумерный массив. Найти все различные строки

In [24]:
Z = np.random.randint(0, 2, (6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]]


19. Даны векторы A и B, написать einsum эквиваленты функций inner, outer, sum и mul

In [39]:
A=np.ones(5)
B=np.array([1,2,3,4,5])

print(np.einsum('i,i', A, B))    # np.inner(A, B)
print(np.einsum('i,j', A, B))    # np.outer(A, B)
print(np.einsum('i->', A))       # np.sum(A)
print(np.einsum('i,i->i', A, B)) # np.mul(A, B)

15.0
[[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]
5.0
[1. 2. 3. 4. 5.]
