---
                                            Московский Авиационный Институт  
                                      (Национальный Исследовательский Университет)  
        
                
                 
    Институт №8 «Информационные технологии и прикладная математика»  
    Кафедра 806 «Вычислительная математика и программирование» 
    Дисциплина: «Разработка ПО для высокопроизводительных систем»        
                



                                            Лабораторная работа по Numpy №2  
    
                                            
                                            
                                            
                                                                                Группа: М8О-103М-20  
                                                                                Студент: Никитина Анна Евгеньевна  
                                                                                Преподаватель: Поповкин Александр Викторович  
                                                                                
                                                                                
                                                                                
                                                     Москва, 2020  
                                                         
---

In [33]:
import numpy as np

1. Перемножить матрицы 5x3 и 3x2

In [34]:
a=np.ones((5,3))
b=np.random.random((3,2))
c=np.dot(a,b)
print(a)
print(b)
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.14775783 0.43805342]
 [0.9823317  0.87147206]
 [0.70880962 0.91828593]]
[[1.83889914 2.22781141]
 [1.83889914 2.22781141]
 [1.83889914 2.22781141]
 [1.83889914 2.22781141]
 [1.83889914 2.22781141]]


2. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [35]:
a=np.arange(11)
a[(a>3)&(a<8)]*=-1
print(a)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


3. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [36]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


4. Есть генератор, сделать с его помощью массив

In [131]:
def generate():
    for x in range(5):
        yield x
#d=np.fromiter(range(5),dtype=float,count=-1)
d=np.fromiter(generate(),dtype=float,count=-1)
print(d)

[0. 1. 2. 3. 4.]


5. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [106]:
a = np.linspace(0,1,12)[1:-1]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


6. Отсортировать вектор

In [107]:
a = np.random.random(10)
a.sort()
print(a)

[0.00124466 0.00536928 0.00695785 0.11787951 0.21463782 0.53969106
 0.75901281 0.92507308 0.9540821  0.98977181]


7. Проверить, одинаковы ли 2 numpy массива

In [109]:
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)
equal = np.allclose(a,b)
print(equal)

False


8. Сделать массив неизменяемым

In [108]:
a = np.zeros(10)
a.flags.writeable = False
a[0] = 1

ValueError: assignment destination is read-only

9. Дан массив 10x2 (точки в декартовой системе координат), преобразовать в полярную

In [111]:
a = np.random.random((10,2))
x,y = a[:,0], a[:,1]
r = np.hypot(x, y)
t = np.arctan2(y,x)
print(r)
print(t)

[0.79425429 0.06575917 0.62450342 0.23039573 0.45813324 0.43158099
 0.89074548 0.74149511 1.33026872 0.85112372]
[1.05896827 0.27830555 0.66489426 1.37989407 0.85383454 0.79840993
 0.27893067 0.94766461 0.74220959 0.57834715]


9. Заменить максимальный элемент на ноль

In [112]:
a = np.random.random(10)
a[a.argmax()] = 0
print(a)

[0.17059733 0.36540047 0.32473745 0.10872313 0.22030666 0.17026056
 0.         0.06872419 0.74277205 0.31495986]


10. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [113]:
a = np.zeros((5,5), [('x',float),('y',float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(a)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


11. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [114]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


12. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [80]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


13. Напечатать все значения в массиве

In [123]:
n=5
a = np.random.random((n,n))
np.set_printoptions(threshold=n*n+1)
print(a)

[[0.5410033  0.94386071 0.83777927 0.06617106 0.53380538]
 [0.1898413  0.96537203 0.98962528 0.46680138 0.8981692 ]
 [0.38048522 0.4474237  0.38139239 0.71182018 0.05742237]
 [0.83778596 0.37746199 0.72928287 0.42918051 0.80371012]
 [0.68684677 0.08714763 0.2255283  0.9064711  0.4837432 ]]


14. Найти ближайшее к заданному значению число в заданном массиве

In [77]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

2


15. Создать структурированный массив, представляющий координату (x,y) и цвет (r,g,b)

In [76]:
 Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-76-6f1aa4d7a2ff>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


16. Дан массив (100,2) координат, найти расстояние от каждой точки до каждой

In [75]:
import scipy.spatial
Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.1392159  0.52712279 0.37379579 0.44234404 0.48372518
  0.46874624 0.06688751 0.15229966 0.63384606]
 [0.1392159  0.         0.50690831 0.31980856 0.3372285  0.55004527
  0.53134417 0.1947611  0.28335821 0.5628661 ]
 [0.52712279 0.50690831 0.         0.20262767 0.33660659 0.32624628
  0.30679034 0.58425812 0.64095563 0.23004458]
 [0.37379579 0.31980856 0.20262767 0.         0.17131727 0.40467906
  0.38183186 0.43847802 0.51167692 0.26141737]
 [0.44234404 0.3372285  0.33660659 0.17131727 0.         0.57596556
  0.55311673 0.50888548 0.59368828 0.26000991]
 [0.48372518 0.55004527 0.32624628 0.40467906 0.57596556 0.
  0.02284934 0.50994774 0.52156951 0.55466614]
 [0.46874624 0.53134417 0.30679034 0.38183186 0.55311673 0.02284934
  0.         0.49723173 0.51229388 0.53438562]
 [0.06688751 0.1947611  0.58425812 0.43847802 0.50888548 0.50994774
  0.49723173 0.         0.08874002 0.69921342]
 [0.15229966 0.28335821 0.64095563 0.51167692 0.59368828 0.52156951
  0.51229388 0.08874

17. Преобразовать массив из float в int

In [129]:
a = np.arange(10, dtype=float)
b = a.astype(int)
print(a)
print(b)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


18. Дан файл:
   1,2,3,4,5   
   6,,,7,8   
   ,,9,10,11   
   Как прочитать его?   

In [68]:
Z = np.genfromtxt("data.dat", delimiter=",")

OSError: data.dat not found.

19. Каков эквивалент функции enumerate для numpy массивов?

In [67]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


20. Сформировать 2D массив с распределением Гаусса

In [66]:
x, y = np.meshgrid(np.linspace(-1,1,5), np.linspace(-1,1,5))
d = np.hypot(x, y)
sigma, mu = 1.0, 0.0
g = np.exp(-((d - mu) ** 2 / (2.0 * sigma ** 2)))
print(g)

[[0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.60653066 0.8824969  1.         0.8824969  0.60653066]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]]


21. Случайно расположить p элементов в 2D массив

In [63]:
n = 5
p = 3
c= [5, 27, 48]
a = np.zeros((n,n))
np.put(a, [3, 7, 20], c)
print(a)

[[ 0.  0.  0.  5.  0.]
 [ 0.  0. 27.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [48.  0.  0.  0.  0.]]


22. Отнять среднее из каждой строки в матрице

In [48]:
x = np.random.rand(5, 10)
y = x - x.mean(axis=1, keepdims=True)
print(y)

[[-0.30731597  0.01097356 -0.04587068  0.17313212 -0.0363063  -0.20638294
   0.51828798 -0.11555213  0.30059898 -0.29156463]
 [-0.40991986  0.39793089 -0.40351044 -0.37592396  0.44848285 -0.0970376
   0.04385164  0.18035431  0.23050207 -0.01472988]
 [-0.38689078  0.30782059  0.02304141 -0.05433326  0.13477484 -0.1598661
   0.12957102  0.30115682 -0.32638632  0.03111179]
 [ 0.28047505  0.16924302 -0.33518039 -0.26668345  0.22316987  0.00190231
  -0.25610079 -0.14438421  0.14153808  0.18602052]
 [-0.34058375  0.37962893 -0.28883781  0.33873334  0.17656836  0.22003527
   0.30818888  0.02643181 -0.24195739 -0.57820764]]


23. Отсортировать матрицу по n-ому столбцу

In [45]:
a = np.random.randint(0,10,(3,3))
n = 1
print(a)
print(a[a[:,n].argsort()])

[[1 3 5]
 [1 8 3]
 [0 2 6]]
[[0 2 6]
 [1 3 5]
 [1 8 3]]


24. Определить, есть ли в 2D массиве нулевые столбцы

In [72]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


25. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [71]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[6. 5. 2. 2. 2. 2. 1. 1. 4. 5.]


26. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [69]:
w,h = 16,16
I = np.random.randint(0, 2, (h,w,3)).astype(np.ubyte)
F = I[...,0] * 256 * 256 + I[...,1] * 256 + I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


27. Дан четырехмерный массив, посчитать сумму по последним двум осям

In [70]:
A = np.random.randint(0,10, (3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[44 26 64 51]
 [72 50 67 39]
 [47 67 47 33]]


28. Найти диагональные элементы произведения матриц

In [43]:
a=np.random.random((5,3))
b=np.random.random((3,2))
c=np.diag(np.dot(a, b))
print(c)

[1.46778858 0.94427569]
