##### Лабораторная работа по Numpy №1
  *гр.М8О-103М-20  
  Никитина Анна  
  дата сдачи: 07.11.2020*


Импортировать NumPy под именем np

In [1]:
import numpy as np

Напечатать версию и конфигурацию

In [2]:
print(np.__version__)
np.show_config()

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [4]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Создать вектор размера 10, заполненный единицами

In [5]:
a=np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Создать вектор размера 10, заполненный числом 2.5

In [6]:
a=np.full(10,2.5)
print(a)

[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]


Как получить документацию о функции numpy.add из командной строки?

In [8]:
python3 -c "import numpy; numpy.info(numpy.add)"

SyntaxError: invalid syntax (<ipython-input-8-e4a7e6a4f2e9>, line 1)

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [9]:
a=np.zeros(10)
a[5]=1
print(a)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


Создать вектор со значениями от 10 до 49

In [11]:
a=np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Развернуть вектор (первый становится последним)

In [12]:
a=np.arange(1,5)
a=a[::-1]
print(a)

[4 3 2 1]


Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [15]:
a=np.arange(0,9)
a=a.reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [22]:
a=[1,2,0,0,4,0]
b=np.nonzero(a)
print(b)

(array([0, 1, 4], dtype=int64),)


Создать массив 3x3x3 со случайными значениями

In [25]:
a=np.random.random((3,3,3))
print(a)

[[[0.25104767 0.35351035 0.17187432]
  [0.49101945 0.87265766 0.40863074]
  [0.61639683 0.5662246  0.45176972]]

 [[0.34253392 0.75811863 0.66896836]
  [0.00827846 0.63961122 0.92874348]
  [0.40079058 0.56217375 0.56512187]]

 [[0.90832076 0.73362185 0.84482095]
  [0.42532696 0.38280741 0.75251817]
  [0.08771358 0.64539124 0.9290715 ]]]


Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [27]:
a=np.random.random((10, 10))
b=a.min()
c=a.max()
print("Minimum a = ", b)
print("Maximum a = ", c)

Minimum a =  0.02802057042245043
Maximum a =  0.9701107884248834


Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [32]:
a=np.random.random(30)
b=a.mean()
print(b)

0.432714303944605


Создать матрицу с 0 внутри, и 1 на границах

In [34]:
a=np.ones((5,5))
a[1:-1,1:-1]=0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Выяснить результат следующих выражений   
  (	0 * np.nan   
  	np.nan == np.nan  
	np.inf > np.nan  
	np.nan - np.nan)  

In [52]:
0 * np.nan   
print(np.nan == np.nan)  
print(np.inf > np.nan)
print(np.nan - np.nan)

False
False
nan


Создать 5x5 матрицу с 1,2,3,4 под диагональю

In [40]:
a=np.zeros((5,5))
l=1
for i in range(5):
    for j in range(5):
        if i==j:
            a[i,j]=l
            l+=1
    
print(a)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


Создать 8x8 матрицу и заполнить её в шахматном порядке

In [43]:
a=np.zeros((8,8))
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [50]:
print(np.unravel_index(100, (6, 7, 8)))

(1, 5, 4)


Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [51]:
a= np.tile(np.array([[0,1],[1,0]]), (4,4))
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
